chore(litmus-portal): Added date filter in workflows table and some important refactorings
litmuschaos/litmus pull request #1962
Opened 2020-09-03 11:45 UTC by amityt

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>

## Proposed changes

This PR adds :
- Date filter in the workflows table
- Important refactoring in the Browse Workflow Section
- Minor CSS fixes

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-09-03 11:57 UTC, arkajyotiMukherjee requested changes

2020-09-03 11:57 UTC, arkajyotiMukherjee commented on litmus-portal/frontend/src/components/Sections/ChaosWorkflows/ScheduleWorkflow/styles.ts
> +    padding: '25px 20px',
can we use theme.spacing here

2020-09-03 12:19 UTC, arkajyotiMukherjee submitted a review, later dismissed
LGTM

2020-09-03 12:23 UTC, rajdas98 submitted a review, later dismissed

2020-09-03 12:52 UTC, S-ayanide submitted a review, later dismissed

2020-09-03 16:40 UTC, Jonsy13 approved these changes

2020-09-04 12:02 UTC, S-ayanide approved these changes

2020-09-04 12:11 UTC, arkajyotiMukherjee approved these changes
LGTM

2020-09-04 12:24 UTC, rajdas98 approved these changes

2020-09-04 12:25 UTC, merged