chore(litmus-portal): Added user avatar selection modal
litmuschaos/litmus pull request #2119
Opened 2020-09-29 04:21 UTC by saswatamcode

## Proposed changes
Added the user avatar selection modal which allows the user to select an avatar from eight different avatars as per the figma design. 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Special notes for your reviewer:
Currently the avatar that is selected is stored as a local state in `UserDetails` as a string containing the path of the avatar svg. Will be integrated will backend later. This PR implements the changing functionality.

2020-10-05 05:05 UTC, arkajyotiMukherjee requested changes

2020-10-05 05:05 UTC, arkajyotiMukherjee commented on litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/ChooseAvatarModal/index.tsx
> +                className={classes.av}
use better and more descriptive classnames

2020-10-05 05:05 UTC, arkajyotiMukherjee commented on litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/ChooseAvatarModal/index.tsx
> +        Choose an avatar
put in translation file

2020-10-05 05:05 UTC, arkajyotiMukherjee commented on litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
> +              Edit Photo
same

2020-10-05 07:19 UTC, arkajyotiMukherjee approved these changes
LGTM cc: @S-ayanide

2020-10-06 11:17 UTC, Saranya-jena approved these changes
LGTM

2020-10-06 11:36 UTC, merged