chore(litmus-portal): Refactor of Unimodal and Button
litmuschaos/litmus pull request #2199
Opened 2020-10-07 04:47 UTC by saswatamcode

## Proposed changes
This PR removes the margins set in `ButtonFilled` and `ButtonOutline` components, and applies the required style changes in the components using them. Also includes refactor of `Unimodal` to extend material-ui `ModalProps`, which will make it more modular, and style changes that are required for correct rendering of close button for the modal.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Special notes for your reviewer:
There are no such functional changes.

2020-10-07 09:34 UTC, Saranya-jena commented
/preview 10

2020-10-14 05:47 UTC, Saranya-jena commented
/preview 10

2020-10-14 06:12 UTC, Saranya-jena commented
@saswatamcode Can attach some screenshots of the modals here?

2020-10-14 06:23 UTC, saswatamcode commented
Sure @Saranya-jena!
![Screenshot 2020-10-14 at 11 51 19 AM](https://user-images.githubusercontent.com/51132453/95951262-c22f9d80-0e13-11eb-9b07-84dce4783719.png)
![Screenshot 2020-10-14 at 11 49 21 AM](https://user-images.githubusercontent.com/51132453/95951284-c5c32480-0e13-11eb-84ab-0152f07d4801.png)
![Screenshot 2020-10-14 at 11 46 46 AM](https://user-images.githubusercontent.com/51132453/95951286-c65bbb00-0e13-11eb-9f0d-5b221660d043.png)
![Screenshot 2020-10-14 at 11 46 25 AM](https://user-images.githubusercontent.com/51132453/95951289-c6f45180-0e13-11eb-9a53-92b43a9ecf6f.png)

2020-10-14 06:37 UTC, Saranya-jena approved these changes
LGTM

2020-10-16 12:03 UTC, Saranya-jena submitted a review, later dismissed

2020-10-20 04:20 UTC, S-ayanide requested changes

2020-10-20 04:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
> +                  <div>Cancel</div>
```suggestion
                  Cancel
```

2020-10-20 04:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
> +                  <div>Save</div>
```suggestion
                  Save
```

2020-10-20 04:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
> +                  </div>
```suggestion
                    <ResultTable
                      testValue={testWeights}
                      testNames={testNames}
                    />
```

2020-10-20 04:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
> +                        <div>Got it</div>
```suggestion
                        Got it
```

2020-10-20 04:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
> +                  <div className={classes.gotItBtn}>
This styling only has a margin-bottom. Can we add it along with ButtonFilled and make the code smaller!

2020-10-21 04:54 UTC, S-ayanide submitted a review, later dismissed

2020-10-21 14:33 UTC, S-ayanide commented
/preview 10

2020-10-21 14:35 UTC, amityt submitted a review, later dismissed

2020-10-21 14:35 UTC, Saranya-jena submitted a review, later dismissed

2020-10-21 15:17 UTC, S-ayanide approved these changes

2020-10-21 15:18 UTC, amityt approved these changes

2020-10-21 15:24 UTC, merged