External Agent Graphql and Backend Integration | Table Section | Cluster Info |Connect Target
litmuschaos/litmus pull request #2211
Opened 2020-10-08 07:06 UTC by oumkale

## Proposed changes

This PR have External Agent Graphql and Backend Integration | Table Section | Cluster Info |Connect Target
## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-10-08 07:25 UTC, amityt requested changes

2020-10-08 07:25 UTC, amityt commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
> +    color: '#CA2C2C',
Can we take the colors from theme?

2020-10-08 07:25 UTC, amityt commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +      cluster_name: Math.random().toString(36).substring(7), // 'oumkale-agent',
Is the commented text required?

2020-10-08 07:25 UTC, amityt commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> +        return p.includes(filters.status.toLowerCase());
Condition for is_active when `true` is not there.

2020-10-08 07:59 UTC, Saranya-jena requested changes

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
> +    background: 'rgba(16, 155, 103, 0.1)',
Can you add this colour to themes if not present?

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
> +    marginRight: theme.spacing(2.5),
here also

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
> +          <Typography variant="h4">{t('targets.connectHome.head')}</Typography>
Are the font sizes similar to that of the design?

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +  // const [modal, setModal] = React.useState(false);
You can remove this comment if not required for later.

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +              // setModal(true)
here also

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +              */}
Are these required? else you can remove

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
> +// import { useTranslation } from 'react-i18next';
can you remove this unused import?

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> +                        {' '}
can you remove this

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
> +    backgroundColor: 'rgba(16, 155, 103, 0.1)',
add it to theme colours

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
> +    color: '#CA2C2C',
use theme colours

2020-10-08 07:59 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
> +            // focused
can you remove this comment

2020-10-09 08:09 UTC, oumkale commented
@amityt @Saranya-jena . PTAL

2020-10-09 14:32 UTC, amityt requested changes

2020-10-09 14:32 UTC, amityt commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> +                        {t('workflowCluster.header.formControl.tableStatus')}
This can be removed from IconButton

2020-10-09 14:32 UTC, amityt commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> +                        {t('workflowCluster.header.formControl.tableCluster')}
Same here

2020-10-09 15:53 UTC, Jonsy13 requested changes

2020-10-09 15:53 UTC, Jonsy13 commented on litmus-portal/frontend/src/containers/app/App.tsx
> +        <Route exact path="/settings" component={Settings} />
Why is this /settings route needed?

2020-10-09 15:53 UTC, Jonsy13 commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
> +  },
CSS for both completed and failed are almost same...can you please follow `${}${}` format

2020-10-10 05:59 UTC, ishangupta-ds requested changes

2020-10-10 05:59 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
> +              <img alt="delete" src="./icons/bin-red.svg" />
```suggestion
              <img alt="delete" src="/icons/bin-red.svg" />
```

2020-10-10 06:02 UTC, ishangupta-ds approved these changes
LGTM.

2020-10-10 07:05 UTC, amityt approved these changes

2020-10-10 07:11 UTC, Jonsy13 approved these changes

2020-10-10 07:17 UTC, Jonsy13 commented
/run-unit

2020-10-10 07:22 UTC, oumkale commented
/ merge

2020-10-10 11:37 UTC, merged