German readme
litmuschaos/litmus pull request #2281
Opened 2020-10-17 17:08 UTC by glumand

## Proposed changes

First translation of the English README to German.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
None.

## Special notes for your reviewer:
I have not added the links to the German version in the Translations-file, because I did not think I should do so. Also I did not add the new "flags-symbols" because I don't know how this would work.

2020-10-18 13:37 UTC, S-ayanide requested changes
Thanks for sending a PR 🎉 

Can you please make the following changes that have been requested! Thank you.

2020-10-18 13:37 UTC, S-ayanide commented on translations/README-ge.md
> +[🇰🇷](translations/README-ko.md) [🇨🇳](translations/README-chn.md)
Please add [🇬🇧] (https://github.com/litmuschaos/litmus/blob/master/README.md)
And change the links for the above as such
```suggestion
[🇰🇷](https://github.com/litmuschaos/litmus/blob/master/translations/README-ja.md) [🇨🇳](https://github.com/litmuschaos/litmus/blob/master/translations/README-chn.md)
```

2020-10-18 13:37 UTC, S-ayanide commented on translations/README-ge.md
> +    Stabilität des Endproduktes zu steigern.
This won't be a sub-point, please revert it back as the main point in this list.
```suggestion
- **Für SREs**: Mit Litmus können Chaos-Experimente geplant durchgeführt
  werden um möglichst früh Schwächen in Anwendungen zu finden und die
  Stabilität des Endproduktes zu steigern.
```

2020-10-20 04:12 UTC, S-ayanide requested changes
I think you forgot to add a `:` in front of gb. Could you please make that minor modification! Thanks

2020-10-20 04:12 UTC, S-ayanide commented on translations/README-ge.md
> +[🇰🇷](https://github.com/litmuschaos/litmus/blob/master/translations/README-ko.md) [🇨🇳](https://github.com/litmuschaos/litmus/blob/master/translations/README-chn.md) [gb](https://github.com/litmuschao
```suggestion
[🇰🇷](https://github.com/litmuschaos/litmus/blob/master/translations/README-ko.md) [🇨🇳](https://github.com/litmuschaos/litmus/blob/master/translations/README-chn.md) [🇬🇧](https://github.com/litmuschaos/litmus/blob/master/README.md)
```

2020-10-20 18:50 UTC, glumand commented on translations/README-ge.md
> +[🇰🇷](https://github.com/litmuschaos/litmus/blob/master/translations/README-ko.md) [🇨🇳](https://github.com/litmuschaos/litmus/blob/master/translations/README-chn.md) [gb](https://github.com/litmuschao
Jap, sure. I hope it works now. :)

2020-10-21 07:28 UTC, christopherfriedrich requested changes
Great work @glumand . I have noticed some small errors. Could you please fix them?.

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +  Kubernetes-Node mit dem Chaos-Experiment zu verbinden. Der Chaos-Engine wird
```suggestion
  Kubernetes-Node mit dem Chaos-Experiment zu verbinden. Die Chaos-Engine wird
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +Die Chaos-Experimente werden auf <a href="https://hub.litmuschaos.io" target="_blank">hub.litmuschaos.io</a> gehostet. Das ist die zentrale Stelle, an der die Entwicker von Anwendungen oder die Nutze
```suggestion
Die Chaos-Experimente werden auf <a href="https://hub.litmuschaos.io" target="_blank">hub.litmuschaos.io</a> gehostet. Das ist die zentrale Stelle, an der die Entwickler von Anwendungen oder die Nutzer ihre Chaos-Experimente teilen, sodass diese genutzt werden können, um die Belastbarkeit und Sicherheit der Anwendung im Endeinsatz weiter zu verbessern. 
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +  Chaos-Experimente als Schritt in der Pipeline genutzt werden um Bugs zu
```suggestion
  Chaos-Experimente als Schritt in der Pipeline genutzt werden, um Bugs zu
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +  werden um möglichst früh Schwächen in Anwendungen zu finden und die
```suggestion
  werden, um möglichst früh Schwächen in Anwendungen zu finden und die
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +(_Senden Sie bitte eine PR an die Seite wenn Sie mit Ihren Anwendungen oder
```suggestion
(_Senden Sie bitte eine PR an die Seite, wenn Sie mit Ihren Anwendungen oder
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +[ROADMAP](./ROADMAP.nd) kann man dazu mehr finden. Für Details zu den
```suggestion
gelistet. Die meisten offenen Punkte sind bereits Teil der [ROADMAP](./ROADMAP.md). Für Details zu den
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +    Ermessensfreiraum sind empfohlen wenn Entwicker und Admins Zugang zu den
```suggestion
    Ermessensfreiraum sind empfohlen wenn Entwicker und Administratoren Zugang zu den
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +  benutzen werden die empfohlenen Sicherheitsrichtlinien dokumentiert.
```suggestion
  benutzen, werden die empfohlenen Sicherheitsrichtlinien dokumentiert.
```

2020-10-21 07:28 UTC, christopherfriedrich commented on translations/README-ge.md
> +  kreiert wenn Experimente vom Chaos-Enginge ausgeführt werden.
```suggestion
  kreiert, wenn Experimente vom Chaos-Enginge ausgeführt werden.
```

2020-10-21 13:24 UTC, christopherfriedrich commented on translations/README-ge.md
> +  Kubernetes-Node mit dem Chaos-Experiment zu verbinden. Das Chaos-Engine wird
```suggestion
  Kubernetes-Node mit dem Chaos-Experiment zu verbinden. Die Chaos-Engine wird
```

2020-10-21 13:29 UTC, glumand commented on translations/README-ge.md
> +  Kubernetes-Node mit dem Chaos-Experiment zu verbinden. Das Chaos-Engine wird
Oh sorry, I skipped that one.

2020-10-21 13:51 UTC, christopherfriedrich requested changes

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +- Wenn plattform-spezifische Chaos-Experimente (vgl. die der AWS, GCP cloud) durchgeführt
```suggestion
- Wenn plattform-spezifische Chaos-Experimente (vgl. die der AWS, GCP ´Cloud) durchgeführt
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +  werden sollen, werden die nötigen Informationen über Kubernetes Secret
```suggestion
  werden sollen, werden die nötigen Informationen über Kubernetes Secrets
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +Litmus ist unter Apache License, Version 2.0 zugelassen. Die komplette Lizenz
```suggestion
Litmus ist unter der Apache License, Version 2.0 zugelassen. Die komplette Lizenz
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +von Litmus genutzt werden laufen eventuell unter anderen Lizenzen, bitte
```suggestion
von Litmus genutzt werden, laufen eventuell unter anderen Lizenzen, bitte
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +- **Für CI-pipelines**: In der kontinuierlichen Integration können
```suggestion
- **Für CI-Pipelines**: In der Continuous Integration können
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +Erste Informationen findet man in den <a href="https://github.com/litmuschaos/community-charts/blob/master/CONTRIBUTING.md" target="_blank">Guildelines für Mitwirkende des Chaos Hub (Seite aktuell no
```suggestion
Erste Informationen findet man in den <a href="https://github.com/litmuschaos/community-charts/blob/master/CONTRIBUTING.md" target="_blank">Guidelines für Mitwirkende des Chaos Hub (Seite aktuell noch auf Englisch)</a>
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +Entwicklungen Litmus zum Chaos
```suggestion
(_Senden Sie bitte eine PR an die Seite, wenn Sie in Ihren Anwendungen oder während der
Entwicklung Litmus zum Chaos
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +    Ermessensfreiraum sind empfohlen wenn Entwickler und Administratoren Zugang zu den
```suggestion
    Docker-Socket installiert werden. Sinnvolles Management ist empfohlen wenn Entwickler und Administratoren Zugang zu den
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +ist auf folgender Seite zu finden: [LIZENZ](./LICENSE). Einige Projekte, die
```suggestion
ist auf folgender Seite zu finden: [Lizenz](./LICENSE). Einige Projekte, die
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +bei der jeweiligen Anwendung nach.
```suggestion
bei dem jeweiligen Projekt nach.
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +Die Litmus Gemeinschaft trifft sich immer am dritten Mittwoch jeden Monats um
```suggestion
Die Litmus Community trifft sich immer am dritten Mittwoch jeden Monats um
```

It is already a common word in german.

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +Kommunikationsmedien und Anwendungen, die zum Austausch genutzt werden:
```suggestion
Kommunikationsmedien zum Austausch und weitere Informationen:
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +gelistet. Die meisten offenen Punkte sind bereits Teil der [ROADMAP](./ROADMAP.nd). Für Details zu den
```suggestion
Ein paar relevante Dinge, die bei der Arbeit mit Litmus zu beachten sind, sind im Folgenden
aufgelistet. Die meisten offenen Punkte sind bereits Teil der [Roadmap](./ROADMAP.nd). Für Details zu den
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +jeweilige Dokumentation unter [Dokumentation der Experimente](https://docs.litmuschaos.io/docs/pod-delete/).
```suggestion
jeweilige [Dokumentation](https://docs.litmuschaos.io/docs/pod-delete/).
```

2020-10-21 13:51 UTC, christopherfriedrich commented on translations/README-ge.md
> +  Kubernetes-Resources auf einem Cluster. Im Falle von air-gapped Umgebungen
```suggestion
  Kubernetes-Resourcen auf einem Cluster. Im Falle von air-gapped Umgebungen
```

2020-10-24 21:42 UTC, christopherfriedrich approved these changes
Looks fine for me as a native speaker. Thanks for your contribution @glumand

cc @S-ayanide

2020-10-25 18:21 UTC, glumand commented
Thank you @christopherfriedrich and also thanks for the help. Would you mind marking the request as hacktoberfest-accepted? I will keep on changing requested things nevertheless.

2020-10-31 07:07 UTC, ksatchit approved these changes

2020-10-31 07:09 UTC, merged

2020-11-25 15:01 UTC, prithvi1307 commented
@glumand Can you please share your email address here for us to send you swags?

2020-11-25 16:12 UTC, glumand commented
> @glumand Can you please share your email address here for us to send you swags?

My email address is trundle13@googlemail.com :)