Added Endpoints for Hub Status and Repository resync support.
litmuschaos/litmus pull request #2299
Opened 2020-10-28 14:28 UTC by Jonsy13

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

**This PR will :**
**- Add Repository sync support ( To be used if cloned repo doesn't exist locally due to some issue).**
**- Add Hub status endpoint for getting the status of all myhubs of user.**
**- Refactored the code for myhub.**

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-10-28 17:03 UTC, ishangupta-ds submitted a review, later dismissed
LGTM.

2020-10-29 07:13 UTC, ishangupta-ds commented
@chandankumar4 PTAL.

2020-10-29 10:24 UTC, chandankumar4 requested changes

2020-10-29 10:24 UTC, chandankumar4 commented on litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
> +	log.Infof("********* Successfully Cloned '%s' Hub *********", gitConfig.HubName)
Not required to print this in the log

2020-10-29 10:24 UTC, chandankumar4 commented on litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
> +	log.Infof("********* Repository syncing completed for '%s' Hub *********", gitConfig.HubName)
Not required to print this in the log

2020-10-29 11:49 UTC, ishangupta-ds approved these changes

2020-10-29 12:04 UTC, rajdas98 requested changes

2020-10-29 12:04 UTC, rajdas98 commented on litmus-portal/graphql-server/pkg/myhub/myhub.go
> +			RepoBranch: userHubs[i].RepoBranch,
> 

> 
```suggestion
	for _, hub := range userHubs {
		sum := 0
		chartsInput := model.ChartsInput{
			HubName:    hub.HubName,
			UserName:   user.GetOutputUser().Username,
			RepoURL:    hub.RepoURL,
			RepoBranch: hub.RepoBranch,
```

2020-10-29 12:30 UTC, rajdas98 approved these changes

2020-10-29 12:42 UTC, ishangupta-ds approved these changes

2020-10-29 13:20 UTC, chandankumar4 approved these changes

2020-10-29 13:23 UTC, merged