Bug fixes in custom workflow section and added autocomplete search for experiment selection
litmuschaos/litmus pull request #2309
Opened 2020-11-03 10:14 UTC by amityt

…r experiments

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-11-03 10:22 UTC, ishangupta-ds requested changes

2020-11-03 10:22 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
> +  const [selectedExp, setSelectedExp] = useState('Select an experiment');
Translation

2020-11-03 10:22 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
> +                        </MenuItem>
Translation

2020-11-03 13:36 UTC, vanshBhatia-A4k9 approved these changes
PTAL at suggestions by @ishangupta-ds, I'm unsure if all can be addressed directly :thinking:

2020-11-04 02:00 UTC, vanshBhatia-A4k9 approved these changes

2020-11-04 02:21 UTC, ishangupta-ds approved these changes
/merge

2020-11-04 02:23 UTC, ishangupta-ds commented
/merge

2020-11-04 07:19 UTC, ishangupta-ds approved these changes

2020-11-04 08:37 UTC, Jonsy13 approved these changes

2020-11-04 09:59 UTC, vanshBhatia-A4k9 approved these changes

2020-11-04 10:24 UTC, merged