changing litmusportal frontend Nginx image to unprivileged nginx image
litmuschaos/litmus pull request #2321
Opened 2020-11-04 15:56 UTC by rajdas98

Signed-off-by: Raj Babu Das <raj.das@mayadata.io>

## Proposed changes

changing litmusportal frontend Nginx image to unprivileged nginx image

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-11-04 16:15 UTC, gdsoumya requested changes

2020-11-04 16:15 UTC, gdsoumya commented on litmus-portal/cluster-k8s-manifest.yml
> +      targetPort: 8080
container port is not updated to 8080 in the deployment spec?

2020-11-06 13:14 UTC, ishangupta-ds commented
can go in as separate image @rajdas98 as discussed. cc: @ajeshbaby

2020-11-15 09:11 UTC, gdsoumya submitted a review, later dismissed

2020-11-15 09:25 UTC, gdsoumya approved these changes

2020-11-15 09:26 UTC, ishangupta-ds approved these changes

2020-11-15 14:23 UTC, merged