Added Delete Cluster Feature For Targets
litmuschaos/litmus pull request #2334
Opened 2020-11-10 12:36 UTC by oumkale

Signed-off-by: Oum Kale <oum.kale@mayadata.io>

## Proposed changes

This PR is adding a Delete cluster feature for targets. We can delete cluster from Cluster Info screens as well as Table now.

Added Delete Cluster
gql integration
Updated mutation, queries, and modal  
Back Button 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-11-10 12:50 UTC, Saranya-jena requested changes

2020-11-10 12:50 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> +  const [deleteCluster] = useMutation<DeleteCluster>(DELETE_CLUSTER, {});
```suggestion
  const [deleteCluster] = useMutation<DeleteCluster>(DELETE_CLUSTER);
```

2020-11-10 12:50 UTC, Saranya-jena commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
> +                      // styles={classes.error}
Can you please remove unused comments?

2020-11-10 12:50 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
> +                        // styles={classes.error}
remove unused comments

2020-11-10 12:50 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
> +
Can you remove this line change?

2020-11-10 12:50 UTC, Saranya-jena commented on litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
> +  const [deleteCluster] = useMutation<DeleteCluster>(DELETE_CLUSTER, {});
```suggestion
  const [deleteCluster] = useMutation<DeleteCluster>(DELETE_CLUSTER);
```

2020-11-11 05:28 UTC, ishangupta-ds requested changes

2020-11-11 05:28 UTC, ishangupta-ds commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +      agent_ns_exists: false,
why are these hardcoded? cc: @rajdas98 @gdsoumya @oumkale 

agent_scope: 'cluster',
agent_namespace: 'litmus',

2020-11-11 05:29 UTC, ishangupta-ds requested changes

2020-11-11 05:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
> +      agent_namespace: 'litmus',
why are these hardcoded? cc: @rajdas98 @gdsoumya @oumkale 

agent_scope: 'cluster',
agent_namespace: 'litmus',

2020-11-11 11:19 UTC, ishangupta-ds approved these changes
LGTM.

2020-11-11 11:56 UTC, amityt approved these changes

2020-11-11 12:22 UTC, Jonsy13 approved these changes

2020-11-11 16:21 UTC, oumkale commented
/merge

2020-11-11 17:32 UTC, merged