Migrated MyHub from users collection to MyHub collection
litmuschaos/litmus pull request #2337
Opened 2020-11-11 15:25 UTC by amityt

## Proposed changes

- Moved MyHub from Users collection to MyHub collection with project ID
![Screenshot from 2020-11-11 20-52-49](https://user-images.githubusercontent.com/40661238/98830185-1c963b00-2460-11eb-935a-90c89e8277b7.png)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2020-11-11 15:43 UTC, Sanjay1611 commented
Can a hub be transferred to another project? What if a project is deleted? Will the hub still exists?

2020-11-11 15:56 UTC, amityt commented
> Can a hub be transferred to another project? What if a project is deleted? Will the hub still exists?

If a project is deleted, the hubs will exist but won't be displayed to the users, since myhubs are a different collection now. If there's an option to transfer the hubs, it's possible , we can just change the project ids accordingly.

2020-11-12 03:57 UTC, rajdas98 requested changes

2020-11-12 03:57 UTC, rajdas98 commented on litmus-portal/graphql-server/pkg/database/mongodb/schema/myhub.go
> +	HubName    string `bson:"hub_name"`
Can we add `updated_at` and `created_at` fields

2020-11-12 12:16 UTC, Sanjay1611 approved these changes

2020-11-12 12:18 UTC, rajdas98 approved these changes

2020-11-12 12:18 UTC, merged