Added Disable Schedule feature + InputField Fixes + Modifications
litmuschaos/litmus pull request #2400
Opened 2021-01-13 09:58 UTC by S-ayanide

## Proposed changes

* Added Disable Schedule Feature
* Fixes minor Breadcrumb + Route issue
* Added onClick InfoToggler and Node renamed to Step
* Dropdown and InputField fixes
* Workflow Name Validation updated
* Fixes WeightSlider by @amityt 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

2021-01-13 14:25 UTC, ishangupta-ds requested changes
@S-ayanide PTAL, translations are required. Rest LGTM.

2021-01-13 14:25 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
> +                  ? 'Once'
Translation required @S-ayanide

2021-01-13 14:25 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
> +              </div>
Translations required @S-ayanide

2021-01-13 14:25 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
>        setYamlStatus('Your code is fine. You can move on !');
use from translation

2021-01-13 14:25 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
> +                  Currently Disabled
use translation

2021-01-15 04:32 UTC, amityt approved these changes

2021-01-15 04:42 UTC, vanshBhatia-A4k9 approved these changes

2021-01-15 04:58 UTC, Jonsy13 approved these changes

2021-01-15 05:04 UTC, merged