chore(litmus-portal: frontend): Added private hub support and curd operation in myhub
litmuschaos/litmus pull request #2402
Opened 2021-01-14 12:00 UTC by amityt

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>

## Proposed changes

This PR adds:
- Private Hub screens in MyHub
- Refresh Hub 
- Edit MyHub screens
- Minor UI refactorings

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
![Screenshot from 2021-01-14 16-32-30](https://user-images.githubusercontent.com/40661238/104588275-228ddf80-568e-11eb-999c-cbbdef8f0a6b.png)
![Screenshot from 2021-01-14 16-32-43](https://user-images.githubusercontent.com/40661238/104588286-27529380-568e-11eb-87cd-30535cb46dd6.png)

2021-01-25 10:24 UTC, Jonsy13 requested changes

2021-01-25 10:24 UTC, Jonsy13 commented on litmus-portal/frontend/public/locales/en/translation.yaml
> +    wait: Please what while we are updating your repo!
It should be "Please wait"

2021-01-25 10:24 UTC, Jonsy13 commented on litmus-portal/frontend/src/pages/MyHub/index.tsx
> +                  <img src="./icons/myhub-crossed.svg" alt="myhub" />
In some places, the dot is added and in some places, it is removed. PTAL @amityt

2021-01-27 05:59 UTC, Jonsy13 approved these changes

2021-01-28 06:50 UTC, S-ayanide approved these changes

2021-01-28 08:59 UTC, merged