chore(litmus-portal): Switch Buttons to Litmus-ui Buttons
litmuschaos/litmus pull request #2456
Opened 2021-02-22 03:42 UTC by saswatamcode

## Proposed changes

This PR switches out `ButtonOutlined` and `ButtonFilled` components with litmus-ui buttons. `ButtonOutline` and `ButtonFilled` have been removed from `components/Buttons`.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

2021-02-23 03:54 UTC, ishangupta-ds approved these changes

2021-02-24 03:46 UTC, S-ayanide requested changes

2021-02-24 03:46 UTC, S-ayanide commented on litmus-portal/frontend/cypress/component/buttons.spec.tsx
> +        disabled={false}
Do we even need this `disabled={false}` line! Since it's enabled by default. Can we try running the test without this line and check once!

2021-02-24 03:46 UTC, S-ayanide commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
>                <ButtonFilled
This button is a secondary button, thus would have `variant="success"`

2021-02-24 03:46 UTC, S-ayanide commented on litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
> +                variant="success"
This is a primary button, thus won't have success variant

2021-02-24 15:57 UTC, S-ayanide approved these changes
LGTM

2021-02-24 15:59 UTC, S-ayanide requested changes

2021-02-24 15:59 UTC, S-ayanide commented on litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
>                <ButtonFilled
This comment is not resolved yet

2021-02-24 16:32 UTC, S-ayanide approved these changes

2021-02-24 16:33 UTC, merged