Added Inital UI Changes for v2 workflow representation screens.
litmuschaos/litmus pull request #2475
Opened 2021-02-25 14:42 UTC by Jonsy13

Signed-off-by: Jonsy13 <vedant.shrotria@mayadata.io>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

**This PR will add UI changes for v2 workflow representation and logs screens.**

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
**There are still changes required with respect to redux and colors. They will come in upcoming PRs.**

2021-03-01 13:25 UTC, amityt approved these changes

2021-03-02 10:47 UTC, S-ayanide requested changes

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
> +        Logs for this step
Can we add this to translation as well!

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
> +    textAlign: 'left',
Should be aligned to the left by default

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
> +    height: '100%',
Height is set to 100% by default

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
> +    <div className={tab === 1 ? classes.rootLight : classes.rootHeader}>
```suggestion
    <div className={`${classes.root} ${tab === 1 ? classes.light : classes.header}`}>
```

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
> +        <div className={classes.headerItemFlex}>
Can we structure the new code better! As in 

class header
-- text 

Something like this. Reference: `ChooseAWorkflowAgent` file

2021-03-02 10:47 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
> +            {t('workflowDetailsView.workflowInfo.runTime.runTimeHeader')}
Can we have the restructuring for all the next files!

2021-03-02 10:58 UTC, S-ayanide commented
Can you please resolve the DeepScan issues!

2021-03-03 11:44 UTC, S-ayanide approved these changes

2021-03-03 12:57 UTC, amityt approved these changes

2021-03-03 13:03 UTC, merged