WIP- New teaming
litmuschaos/litmus pull request #2490
Opened 2021-03-02 17:41 UTC by rajdas98

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-03-02 19:01 UTC, vanshBhatia-A4k9 submitted a review, later dismissed

2021-03-03 06:15 UTC, SarthakJain26 submitted a review, later dismissed

2021-03-03 06:17 UTC, Saranya-jena approved these changes

2021-03-03 06:17 UTC, amityt requested changes

2021-03-03 06:17 UTC, amityt commented on litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
> +    onError: () => {},
Since no action is performed on onError, can this be removed?

2021-03-03 06:17 UTC, amityt commented on litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
> +    onError: () => {},
Same as above

2021-03-03 06:18 UTC, amityt commented
Deepscan is also failing, can you take a look @Saranya-jena @SarthakJain26  @vanshBhatia-A4k9

2021-03-03 06:59 UTC, amityt approved these changes

2021-03-03 07:02 UTC, vanshBhatia-A4k9 approved these changes

2021-03-03 07:03 UTC, SarthakJain26 approved these changes

2021-03-03 07:15 UTC, merged