chore(litmus-portal): Add Add Probe modal
litmuschaos/litmus pull request #2491
Opened 2021-03-03 06:37 UTC by saswatamcode

## Proposed changes

This PR adds the Add Probe modal which will be used in the Tune Workflow screens.
### Screenshots
![Screenshot 2021-03-03 at 11 52 40 AM](https://user-images.githubusercontent.com/51132453/109763868-c6b8ef00-7c18-11eb-85d5-a8cb4f355137.png)
![Screenshot 2021-03-03 at 11 52 54 AM](https://user-images.githubusercontent.com/51132453/109763896-d2a4b100-7c18-11eb-98ed-b3fc665209b1.png)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

2021-03-03 09:33 UTC, ishangupta-ds requested changes
@saswatamcode please add all the translations

2021-03-03 09:33 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="Prom">Prom</MenuItem>
can be used from translations file

2021-03-03 09:33 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              Probe Properties
add translation

2021-03-03 09:33 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="onChaos">onChaos</MenuItem>
translations can be added

2021-03-03 09:33 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +          <div style={{ display: 'flex', width: '100%' }}>
use from styles, avoid inline styling

2021-03-03 09:33 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +                Timeout
translation

2021-03-03 11:25 UTC, ishangupta-ds commented
<img width="1315" alt="Screenshot 2021-03-03 at 4 54 21 PM" src="https://user-images.githubusercontent.com/50652677/109798845-3fcc3c80-7c41-11eb-847d-dd6689a90dfb.png">
<img width="1536" alt="Screenshot 2021-03-03 at 4 54 44 PM" src="https://user-images.githubusercontent.com/50652677/109798851-41960000-7c41-11eb-8935-e2361532af5c.png">
<img width="1536" alt="Screenshot 2021-03-03 at 4 55 07 PM" src="https://user-images.githubusercontent.com/50652677/109798857-435fc380-7c41-11eb-9911-156830d0d370.png">

@saswatamcode PTAL

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="Http">
Can we make them uniform either all pascal or lower case? (preferred lower case)
{ Http, Cmd, K8s, Prom} OR {http, cmd, k8s, prom}

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              {t('createWorkflow.tuneWorkflow.addProbe.labels.probeProp')}
SOT, EOT, Edge,  Continuous, OnChaos all comes under `mode`. refer: https://docs.litmuschaos.io/docs/litmus-probe/

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="SoT">
SOT

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="EoT">
EOT

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              <MenuItem value="onChaos">
OnChaos

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              {t('createWorkflow.tuneWorkflow.addProbe.labels.intervalDelay')}
initialDelaySeconds

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              value={probeData.url}
Is this static or dynamic (changed based on probeType)? The corresponding input options will come based on the selected probe-type?

2021-03-03 14:31 UTC, ispeakc0de commented on litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
> +              value={probeData.expectedResponseCode}
The input schema of http probe has been changed, we don't this field now. Please refer: https://docs.litmuschaos.io/docs/litmus-probe/#httpprobe

2021-03-04 04:48 UTC, S-ayanide commented
@saswatamcode Please align the key-value pairs with a proper design and not just side by side. The Figma design would need updates too. Put the input fields and labels in proper spacing and alignment, 50% or so should be good. Also please check the DeepScan issues.

2021-03-04 14:35 UTC, saswatamcode commented
PR Updated to make inputs dynamic based on Probe Type and for style fixes.
![Screenshot 2021-03-04 at 7 51 03 PM](https://user-images.githubusercontent.com/51132453/109978900-58615300-7d24-11eb-95e1-dbbf8b209a3b.png)
## Probe inputs when type is `http`
![Screenshot 2021-03-04 at 7 51 35 PM](https://user-images.githubusercontent.com/51132453/109978922-5e573400-7d24-11eb-8e16-e21fecf2e619.png)
## Probe inputs when type is `cmd`
![Screenshot 2021-03-04 at 7 51 51 PM](https://user-images.githubusercontent.com/51132453/109979240-b0985500-7d24-11eb-96d9-80c5104d58de.png)
## Probe inputs when type is `k8s`
![Screenshot 2021-03-04 at 7 52 07 PM](https://user-images.githubusercontent.com/51132453/109979373-d58cc800-7d24-11eb-956d-ebfbcb8f1450.png)
## Probe inputs when type is `prom`
![Screenshot 2021-03-04 at 7 52 24 PM](https://user-images.githubusercontent.com/51132453/109979450-eb9a8880-7d24-11eb-9a95-41a1ecf031f0.png)

2021-03-05 00:50 UTC, ishangupta-ds approved these changes
LGTM

2021-03-08 04:59 UTC, S-ayanide approved these changes

2021-03-08 05:00 UTC, merged