Added Kubernetes Objects API with dynamic client
litmuschaos/litmus pull request #2625
Opened 2021-04-01 06:43 UTC by amityt

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>

## Proposed changes

This PR adds:
- Kubernetes Object API
- Dynamic Client to fetch the Kubernetes Obj Data

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-04-01 08:18 UTC, gdsoumya requested changes
- Restructure directory and move `objects` to `cluster` dir
- Check if this works in namespaced scope

2021-04-01 08:18 UTC, gdsoumya commented on litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
> +	}
ClusterID will not work for request mapping use request id, ref PodLog request

2021-04-01 08:18 UTC, gdsoumya commented on litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
> +			KubeObj:   "Data not available",
Send request id too

2021-04-01 09:20 UTC, gdsoumya approved these changes

2021-04-01 09:24 UTC, ishangupta-ds approved these changes

2021-04-01 10:53 UTC, rajdas98 commented
As discussed- 
In this PR, we are sending only a few k8s object data from the subscriber to gql-server. so, we need to send all the data of the k8s object in an unstructured form, and once the server receives the unstructured data, it will parse the response based on the resource type.
cc: @amityt

2021-04-05 07:55 UTC, rajdas98 approved these changes

2021-04-05 07:55 UTC, merged