Added changes for handling Node Phases edge cases. [Omitted/ Skipped/ Error]
litmuschaos/litmus pull request #2779
Opened 2021-05-11 13:46 UTC by Jonsy13

Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

## Proposed changes
**This PR will add a fix for handling all node phases in DAG and Node Details container and one fix for the logout icon route.**

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
**Currently, The colors are added in Hex, which needs to be changed to theme-based.**

**SKIPPED PHASE**

![Screenshot from 2021-05-11 19-07-43](https://user-images.githubusercontent.com/40681425/117824841-6e434500-b28c-11eb-841c-5f5ae35f37e0.png)

**OMITTED PHASE**

![Screenshot from 2021-05-11 19-08-20](https://user-images.githubusercontent.com/40681425/117824900-7a2f0700-b28c-11eb-8666-9b88654ac466.png)

**ERROR PHASE**

![Screenshot from 2021-05-11 19-08-50](https://user-images.githubusercontent.com/40681425/117824955-86b35f80-b28c-11eb-838b-9a93300118d7.png)

**Status Component** - 

![Screenshot from 2021-05-11 19-12-12](https://user-images.githubusercontent.com/40681425/117825523-04776b00-b28d-11eb-990a-98516bd2f6ba.png)
![Screenshot from 2021-05-11 19-12-42](https://user-images.githubusercontent.com/40681425/117825538-07725b80-b28d-11eb-8210-cacc99d156d0.png)
![Screenshot from 2021-05-11 19-13-16](https://user-images.githubusercontent.com/40681425/117825560-0b05e280-b28d-11eb-836d-872f7bbea167.png)

2021-05-11 13:55 UTC, arkajyotiMukherjee approved these changes

2021-05-12 04:00 UTC, Jonsy13 commented
/merge

2021-05-12 09:20 UTC, S-ayanide requested changes

2021-05-12 09:20 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
> +
We need to adhere to the Litmus UI theme colors, we can either add these colors or change them to error success and pending.

2021-05-12 09:26 UTC, S-ayanide commented on litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
> +
**Took a look at Special Notes**

2021-05-12 09:26 UTC, S-ayanide approved these changes

2021-05-12 09:26 UTC, merged