type(bugfix): Fix Editor typing issue
litmuschaos/litmus pull request #2784
Opened 2021-05-12 05:53 UTC by saswatamcode

## Proposed changes

Currently, the `Editor` uses [Ubuntu Mono](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/src/components/YamlEditor/Editor.tsx#L477) font family but this causes issues when typing as it introduces extra spacing between cursor and actual text. Removing the font property fixes this.

### Screenshots
Before fix, (notice space between cursor and text even though there is no tab/space character present which causes unpredictable typing)
![Screenshot 2021-05-12 at 11 12 42 AM](https://user-images.githubusercontent.com/51132453/117924286-23204500-b313-11eb-8855-84d31540c997.png)

After fix, (cursor and text match),
![Screenshot 2021-05-12 at 11 20 59 AM](https://user-images.githubusercontent.com/51132453/117924929-2831c400-b314-11eb-95b5-34f666c6f325.png)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

2021-05-12 05:54 UTC, ishangupta-ds requested changes
Change to litmus-ui font style.

2021-05-13 05:13 UTC, amityt approved these changes

2021-05-13 07:19 UTC, ishangupta-ds approved these changes

2021-05-13 12:14 UTC, S-ayanide approved these changes

2021-05-13 12:14 UTC, merged