chore(litmus-portal): Added image registry frontend integration
litmuschaos/litmus pull request #2786
Opened 2021-05-12 08:15 UTC by amityt

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

## Proposed changes

This PR adds:
- Image registry frontend integration

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-05-12 08:29 UTC, ishangupta-ds requested changes

2021-05-12 08:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +        });
declare in a constants file (with default values)

2021-05-12 08:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +          'litmuschaos'
constant would be better

2021-05-12 08:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +    registry_type: 'Public',
use constant

2021-05-12 08:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +                              image_registry_type: 'Public',
constants needed.

2021-05-12 08:29 UTC, ishangupta-ds commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
> +    marginBottom: theme.spacing(2.5),
use one margin property

2021-05-12 13:59 UTC, ishangupta-ds approved these changes
LGTM

2021-05-13 04:36 UTC, Jonsy13 commented on litmus-portal/frontend/public/locales/en/translation.yaml
> +    additionalInfo: Provide addtional details
Can we fix additional spelling here

2021-05-13 04:39 UTC, S-ayanide approved these changes

2021-05-13 04:39 UTC, S-ayanide commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +        </>
```suggestion
      {listLoading && loading ? (
          <Loader />
```

2021-05-13 04:39 UTC, S-ayanide commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
> +                  </>
Fragments aren't required here, div is already single wrapper

2021-05-13 04:39 UTC, S-ayanide commented on litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
> +    border: `1px solid ${theme.palette.border.main}`,
Could use rem instead for consistency, not an issue though

2021-05-13 04:43 UTC, Jonsy13 approved these changes

2021-05-13 04:58 UTC, S-ayanide approved these changes

2021-05-13 05:14 UTC, merged