Added pre-defined experiment from default chaos hub and workflow_name label in chaos engine
litmuschaos/litmus pull request #2791
Opened 2021-05-12 13:10 UTC by amityt

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

## Proposed changes

This PR adds:
- Pre-defined experiment from Default MyHub
- Workflow_name label in chaos engine

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-05-12 13:12 UTC, ishangupta-ds requested changes

2021-05-12 13:12 UTC, ishangupta-ds commented on litmus-portal/frontend/src/constants.ts
> +
remove this extra line

2021-05-12 14:00 UTC, ishangupta-ds approved these changes
LGTM

2021-05-13 05:13 UTC, S-ayanide approved these changes

2021-05-13 05:27 UTC, Jonsy13 approved these changes

2021-05-13 06:13 UTC, S-ayanide commented
@amityt could you please resolve the conflicts in `constants.ts` and `queries.ts` file! Thank you

2021-05-13 09:25 UTC, merged