type(ux): Added delete option in experiment table, fixed agent select radio buttons and minor ux changes
litmuschaos/litmus pull request #2862
Opened 2021-06-03 13:51 UTC by amityt

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

## Proposed changes

This PR adds:
- Delete experiment option in tune workflow table
- Fixed agent select radio button
- Fixed the units in probes modal
- Minor UX changes

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
![Screenshot from 2021-06-03 18-57-02](https://user-images.githubusercontent.com/40661238/120655990-d6a6d000-c4a0-11eb-9617-1d959ed93e41.png)

2021-06-08 06:22 UTC, Jonsy13 requested changes

2021-06-08 06:22 UTC, Jonsy13 commented on litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
> +            <RadioGroup
@amityt With this approach, This RadioGroup will have only one button under itself.
I think the RadioGroup Component should be out of the map()?

2021-06-08 07:43 UTC, Jonsy13 approved these changes

2021-06-09 04:58 UTC, S-ayanide requested changes

2021-06-09 04:58 UTC, S-ayanide commented on litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
> +    margin: theme.spacing(2),
```suggestion
    margin: theme.spacing(2, 0),
```

2021-06-09 07:18 UTC, S-ayanide approved these changes

2021-06-09 07:18 UTC, merged