Added engine context in chaos data
litmuschaos/litmus pull request #2954
Opened 2021-06-30 07:31 UTC by SarthakJain26

Signed-off-by: SarthakJain26 <sarthak@chaosnative.com>

Added engine context in chaos data

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-06-30 07:32 UTC, ishangupta-ds requested changes

2021-06-30 07:32 UTC, ishangupta-ds commented on litmus-portal/cluster-agents/subscriber/pkg/types/event.go
> +	EngineContext		   string				 `json:"engineContext"`
please format using gofmt

2021-06-30 07:32 UTC, ishangupta-ds commented on litmus-portal/graphql-server/pkg/chaos-workflow/types.go
> +	EngineContext		   string				   `json:"engine_context"`
same here

2021-06-30 07:38 UTC, arkajyotiMukherjee approved these changes

2021-06-30 07:45 UTC, ishangupta-ds approved these changes

2021-07-01 05:05 UTC, gdsoumya approved these changes

2021-07-01 05:06 UTC, merged