Add API Route /status into authn-server
litmuschaos/litmus pull request #3025
Opened 2021-07-15 16:32 UTC by Vr00mm

## Proposed changes

We can with kubernetes or docker check if a component is ready or not.
This PR add a /status API route into the authn component that kubernetes can request

The status function get the list of user to be sure all is UP (mongo, process, etc) and then return a 200 {status:up} or a 500 {status:down}

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ X] I have signed the commit for DCO to be passed.
- [ X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-07-16 06:27 UTC, Vr00mm commented
![image](https://user-images.githubusercontent.com/87191932/125902162-e1058a78-340d-4803-a50b-e27451b11226.png)

2021-07-21 11:16 UTC, arkajyotiMukherjee approved these changes

2021-07-21 11:18 UTC, ishangupta-ds approved these changes

2021-07-21 11:21 UTC, rajdas98 requested changes
Thanks @Vr00mm for this PR. One check is failed due to the disorder of go imports in this file- ./litmus-portal/authentication/pkg/entities/user.go

2021-07-22 05:36 UTC, rajdas98 approved these changes

2021-07-22 05:39 UTC, merged