Adding checks for invalid or duplicate chaos injection events and verdicts
litmuschaos/litmus pull request #3109
Opened 2021-08-10 07:47 UTC by ishangupta-ds

## Proposed changes

* Added check for slicing bounds for cases when chaos is not injected successfully
* Updated scrape job and service monitor for chaos-exporter to relabel instance for filtering out unique events and metrics for queries
* updated default chaos event and verdict queries

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes

2021-08-10 07:48 UTC, rajdas98 requested changes

2021-08-10 07:48 UTC, rajdas98 commented on litmus-portal/graphql-server/go.sum
>  github.com/coreos/prometheus-operator v0.34.0/go.mod h1:Li6rMllG/hYIyXfMuvUwhyC+hqwJVHdsDdP21hypT1M=
Can you revert this file changes?

2021-08-10 07:54 UTC, ishangupta-ds commented on litmus-portal/graphql-server/go.sum
>  github.com/coreos/prometheus-operator v0.34.0/go.mod h1:Li6rMllG/hYIyXfMuvUwhyC+hqwJVHdsDdP21hypT1M=
Done @rajdas98

2021-08-18 03:38 UTC, ksatchit approved these changes

2021-08-18 05:26 UTC, rajdas98 approved these changes

2021-08-18 07:20 UTC, merged