Update bug_report.md
litmuschaos/litmus pull request #3358
Opened 2021-11-23 12:14 UTC by mehabhalodiya

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2021-11-23 20:20 UTC, ispeakc0de approved these changes

2021-11-24 04:45 UTC, mehabhalodiya commented
Can you @ispeakc0de  please let me know, is there anything left to do from my side?

2021-11-26 06:51 UTC, neelanjan00 requested changes

2021-11-26 06:51 UTC, neelanjan00 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Where is this stated?**
```suggestion
**Where can this issue be corrected? (optional)**
```

2021-11-26 06:51 UTC, neelanjan00 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- provide additional information about the location that needs to be modified -->
```suggestion
<!-- provide additional information about the file location or directory that needs to be modified to fix this issue, if available -->
```

2021-11-26 12:14 UTC, neelanjan00 approved these changes

2021-12-02 09:18 UTC, mehabhalodiya commented
@rajdas98 Can you PTAL and merge it, if possible?
Thank you.

2021-12-02 12:20 UTC, merged