Updated api docs with optional fields
litmuschaos/litmus pull request #3483
Opened 2022-03-07 08:16 UTC by Saranya-jena

Signed-off-by: Saranya-jena <saranya@chaosnative.com>

## Proposed changes
- Updated API docs with optional fields in few APIs
- Added documentation for /get_projects_stats

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2022-03-08 06:24 UTC, SarthakJain26 approved these changes

2022-03-09 06:06 UTC, Aman-Codes requested changes

2022-03-09 06:06 UTC, Aman-Codes commented on mkdocs/docs/graphql/v2.0.0/api.html
> +          </section>
Could you please change
https://github.com/litmuschaos/litmus/blob/f801670b7327c16b9b80487e0e0c7ffd4ea82df7/mkdocs/docs/graphql/v2.0.0/api.html#L604
to
```
<td>Optional</td>
```

2022-03-09 06:06 UTC, Aman-Codes commented on mkdocs/docs/auth/v2.0.0/swagger.yml
>        produces:
Similar error for `/get_project/{project_id}` and `/get_user_with_project/{username}`

2022-03-30 06:13 UTC, Aman-Codes approved these changes

2022-03-30 07:10 UTC, merged