Rbac validation
litmuschaos/litmus pull request #3486
Opened 2022-03-10 10:21 UTC by SarthakJain26

## Proposed changes

- Added RBAC checks for the following APIs:
DeleteClusterReg, DeleteChaosWorkflow, GeneraterSSHKey, UpdateDashboard, DeleteDashboard, DeleteDataSource, DeleteManifestTemplate, CreateImageRegistry, UpdateImageRegistry, DeleteImageRegistry, ListDataSource, GetPromSeriesList, ListDashboard, GetGitOpsDetails, ListManifestTemplate, GetTemplateManifestByID, ListImageRegistry, GetImageRegistry, TerminateChaosWorkflow, SyncWorkflow, SyncHub

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2022-03-10 10:29 UTC, arkajyotiMukherjee approved these changes

2022-03-10 10:47 UTC, amityt approved these changes

2022-03-10 11:16 UTC, gdsoumya requested changes

2022-03-10 11:16 UTC, gdsoumya commented on litmus-portal/graphql-server/pkg/cluster/handler/handler.go
> +func DeleteCluster(ctx context.Context, projectID string, clusterIds []*string, r store.StateData) (string, error) {
Rename to DeleteClusters

2022-03-10 11:16 UTC, gdsoumya commented on litmus-portal/graphql-server/graph/schema.resolvers.go
> +func (r *mutationResolver) DeleteClusterReg(ctx context.Context, projectID string, clusterIds []*string) (string, error) {
Rename to DeleteClusters. 

TODO refactor : rename Clusters to Agents in the codebase

2022-03-11 06:14 UTC, gdsoumya approved these changes

2022-03-11 08:40 UTC, amityt approved these changes

2022-03-11 13:49 UTC, merged