Fixing subscriber to update CLUSTER_ID and ACCESS_KEY to the agent-secret
litmuschaos/litmus pull request #3546
Opened 2022-04-11 02:05 UTC by rajdas98

The subscriber was updating CLUSTER_ID and ACCESS_KEY in the agent-config map. This PR fixed the logic of the subscriber to update it in agent-secret.

Signed-off-by: Raj Babu Das <raj@chaosnative.com>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2022-04-11 02:06 UTC, rajdas98 commented
Note: Testing is pending.

2022-04-11 04:14 UTC, gdsoumya requested changes

2022-04-11 04:14 UTC, gdsoumya commented on litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
> +	_, err = clientset.CoreV1().Secrets(AgentNamespace).Update(context.TODO(), &corev1.Secret{
Probably need to add secret permissions to subscriber https://github.com/litmuschaos/litmus/blob/035b14eb916ab56ec3f7793330602a0ebe056dc2/litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml#L185

2022-04-14 07:53 UTC, gdsoumya approved these changes

2022-04-15 18:35 UTC, rajdas98 commented
Works fine during testing. Merging this PR

2022-04-15 18:35 UTC, merged