Improve: AWS IAM Integration
litmuschaos/litmus pull request #3650
Opened 2022-06-09 02:48 UTC by QAInsights

## Proposed changes

Improved instructions for AWS IAM Integration and minor edits.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
Fixes https://github.com/litmuschaos/litmus/issues/3649

## Special notes for your reviewer:
NA

2022-06-10 10:04 UTC, neelanjan00 commented on mkdocs/docs/experiments/concepts/IAM/awsIamIntegration.md
> +If you run an experiment and describe one of the pods and verify that the `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables exist.
```suggestion
If you run an experiment and describe one of the pods, you can verify that the `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables exist.
```

2022-10-12 10:20 UTC, avaakash commented
Hi @QAInsights can you please resolve the comments, thank you.

2022-10-13 13:28 UTC, avaakash approved these changes

2022-10-17 04:12 UTC, neelanjan00 approved these changes

2022-10-17 04:19 UTC, neelanjan00 requested changes

2022-10-17 04:19 UTC, neelanjan00 commented on mkdocs/docs/experiments/concepts/IAM/awsIamIntegration.md
> +```bash
```suggestion
```

We can remove this

2022-10-17 04:20 UTC, ispeakc0de approved these changes

2022-10-17 04:39 UTC, neelanjan00 approved these changes

2022-10-17 04:40 UTC, merged