Added UI changes, warning text for SSH method, updated litmusctl commands and minor fixes
litmuschaos/litmus pull request #3717
Opened 2022-08-04 06:49 UTC by Saranya-jena

## Proposed changes

- Added UI changes,
- Added warning text for SSH method, 
- Updated litmusctl commands and minor fixes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2022-08-04 06:58 UTC, SarthakJain26 commented on litmus-portal/frontend/public/locales/en/translation.yaml
>      submit: Update MyHub
Should we update MyHub to ChaosHub?

2022-08-04 06:58 UTC, SarthakJain26 commented on litmus-portal/frontend/public/locales/en/translation.yaml
>      construct: Using experiments from MyHubs
same

2022-08-04 14:46 UTC, amityt requested changes

2022-08-04 14:46 UTC, amityt commented on litmus-portal/frontend/public/locales/en/translation.yaml
> +    copyTargetID: Copy ChaosDelegate ID
`ChaosDelegate` --> `Chaos Delegate`

2022-08-04 14:46 UTC, amityt commented on litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
> +        setName('custom');
Please revert this back! 👀

2022-08-05 05:46 UTC, amityt approved these changes

2022-08-05 06:31 UTC, Jonsy13 approved these changes

2022-08-05 06:31 UTC, merged