feat: Litmus 3.0: Added enhancements in graphql server
litmuschaos/litmus pull request #4019
Opened 2023-06-22 08:01 UTC by Saranya-jena

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-06-26 11:30 UTC, SarthakJain26 requested changes

2023-06-26 11:30 UTC, SarthakJain26 commented on chaoscenter/graphql/definitions/shared/chaos_infrastructure.graphqls
> +  lastWorkflowTimestamp: String
lastExperimentTimestamp* ^^

2023-06-27 04:34 UTC, imrajdas approved these changes

2023-06-27 04:42 UTC, vanshBhatia-A4k9 approved these changes
3.0 🚀

2023-06-27 04:49 UTC, vanshBhatia-A4k9 commented on chaoscenter/graphql/server/graph/chaos_infrastructure.resolvers.go
> +	logrus.WithFields(logFields).Info("request received to delete chaos infrastructures")
```suggestion
func (r *mutationResolver) DeleteInfra(ctx context.Context, projectID string, infraID string) (string, error) {
	logFields := logrus.Fields{
		"projectId":    projectID,
		"chaosInfraId": infraID,
	}

	logrus.WithFields(logFields).Info("request received to delete chaos infrastructure")
```

2023-06-27 06:28 UTC, SarthakJain26 approved these changes
LGTM

2023-06-27 06:30 UTC, merged