[ChaosCenter]: Revoke the token when the user logout
litmuschaos/litmus pull request #4085
Opened 2023-07-12 10:50 UTC by namkyu1999

## Proposed changes

Issue No. #4084 

1. Add `logout` logic to Authentication server
1.1. Add Mongo Schema `revoked-token`
1.2. Add `/logout` endpoint(POST) to Authentication server
1.3. When user logout, blacklist token (createOne to 'revoked-token' collection)
2. AuthMiddleware checks whether tokens are revoked or not. (in authentication-server & graphql-server)
3. Call `/logout` in frontend when logout button clicked

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be maerged before this (if any).

## Special notes for your reviewer:

2023-07-28 05:27 UTC, Saranya-jena requested changes
@namkyu1999 we have to do all these changes in /chaoscenter directory -  auth and web folders

2023-07-28 05:27 UTC, Saranya-jena commented on litmus-portal/authentication/api/main.go
> +		log.Fatalf("failed to create index  %s", err)
instead of doing a fatal can you just log the error, would be great if you can change it for all collections creation

2023-07-28 05:28 UTC, Saranya-jena commented on litmus-portal/authentication/api/handlers/rest/user_handlers.go
> +			"message": "logout succeed",
logout succeed -> successfully logged out

2023-07-28 12:23 UTC, namkyu1999 commented
@Saranya-jena 
I added logic to chaoscenter/authentication, chaoscenter/graphql, and chaoscenter/web :)

2023-08-10 07:45 UTC, Saranya-jena approved these changes
LGTM

2023-08-11 06:42 UTC, hrishavjha requested changes
Hey @namkyu1999, proposed changes looks good to me. Just a small request, we've updated the REST API's setup in `chaoscenter` directory. Can you update the auth API [swagger file](https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/auth/v3.0.0/auth-api.json) and do a `yarn services` to generate frontend API and consume that. For `litmus-portal` directory everything will remain the same this change should only be inside `chaoscenter`. I'll suggest you to make changes in swagger file first and push it so that you can update the [OATS config](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/web/config/oats.config.ts#L12) file with the raw link of your updated swagger file.
We can wait for @Saranya-jena's [PR](https://github.com/litmuschaos/litmus/pull/4118) to get merged first then you can update the swagger file.

2023-08-11 07:49 UTC, namkyu1999 commented
> Hey @namkyu1999, proposed changes looks good to me. Just a small request, we've updated the REST API's setup in `chaoscenter` directory. Can you update the auth API [swagger file](https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/auth/v3.0.0/auth-api.json) and do a `yarn services` to generate frontend API and consume that. For `litmus-portal` directory everything will remain the same this change should only be inside `chaoscenter`. I'll suggest you to make changes in swagger file first and push it so that you can update the [OATS config](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/web/config/oats.config.ts#L12) file with the raw link of your updated swagger file. We can wait for @Saranya-jena's [PR](https://github.com/litmuschaos/litmus/pull/4118) to get merged first then you can update the swagger file.

Hey @hrishavjha , I synchronized the master branch code and updated the swagger file.

2023-08-11 13:35 UTC, namkyu1999 commented
Hey @hrishavjha , Thanks for the detailed explanation. I fixed all that you said.

One thing I want to mention in `chaoscenter/web/src/app/App.tsx`, We use a try-catch statement. But It's not a good idea because we cannot detect what's happening when errors come out. And We cannot use `forceLogout` function because We use them out of LitmusAPIProvider scope. So I deleted a try-catch statement. Is that okay?

2023-08-11 13:53 UTC, hrishavjha approved these changes
Hey @namkyu1999, following changes looks good to me 🚀

2023-08-13 07:05 UTC, SarthakJain26 requested changes
Please rename the `expire_on`  field to `expires_at` in the DB and other places.

2023-08-13 08:00 UTC, namkyu1999 commented
> Please rename the `expire_on` field to `expires_at` in the DB and other places.

@SarthakJain26 I've included your feedback :)

2023-08-14 04:59 UTC, amityt approved these changes
LGTM

2023-08-14 05:10 UTC, SarthakJain26 approved these changes

2023-08-14 05:38 UTC, merged