Remove unused RBACs in GraphQL server
litmuschaos/litmus pull request #4122
Opened 2023-08-09 17:39 UTC by punithnayak

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-08-21 11:43 UTC, Saranya-jena requested changes
go imports are not in order, please fix them by running this command: goimports -w -l ./

2023-08-23 04:45 UTC, Saranya-jena approved these changes
LGTM

2023-08-23 05:45 UTC, namkyu1999 requested changes

2023-08-23 05:45 UTC, namkyu1999 commented on chaoscenter/graphql/server/pkg/authorization/roles.go
Great work! but I think we can remove more unused variables. Can you check out my [GitHub gist](https://gist.github.com/namkyu1999/d7eee6329ca93220b9f116ad3c01d3b5) and update this file?

2023-08-23 08:52 UTC, namkyu1999 commented on chaoscenter/graphql/server/pkg/authorization/roles.go
> go imports are not in order, please fix them by running this command: goimports -w -l ./

backend-checks are failed. Can you try this one again? @punithnayak

2023-08-23 13:14 UTC, punithnayak commented on chaoscenter/graphql/server/pkg/authorization/roles.go
Hey, can you check now?

2023-08-23 13:24 UTC, namkyu1999 commented on chaoscenter/graphql/server/pkg/authorization/roles.go
Resolving a merge conflict please @punithnayak

2023-08-23 14:04 UTC, closed without merging