Added changes required for dex setup for litmus 3.0.0-beta11
litmuschaos/litmus pull request #4163
Opened 2023-09-12 05:43 UTC by Saranya-jena

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-09-12 06:12 UTC, hrishavjha approved these changes

2023-09-12 06:12 UTC, hrishavjha commented on chaoscenter/web/src/controllers/Login/LoginPage.tsx
> +  const dexProjectRole = searchParams.get('projectRole');
```suggestion
  const dexProjectRole = searchParams.get('projectRole') as PermissionGroup;
```

2023-09-12 06:12 UTC, hrishavjha commented on chaoscenter/web/src/controllers/Login/LoginPage.tsx
> +    if (dexToken && dexProjectID) {
```suggestion
    if (dexToken && dexProjectID && dexProjectRole) {
```

2023-09-13 07:19 UTC, SarthakJain26 requested changes

2023-09-13 07:19 UTC, SarthakJain26 commented on chaoscenter/authentication/api/handlers/rest/dex_auth_handler.go
> +				JoinedAt:   time.Now().Unix(),
Please convert it to UnixMilli()

2023-09-13 07:19 UTC, SarthakJain26 commented on chaoscenter/authentication/api/handlers/rest/dex_auth_handler.go
> +				Name:    signedInUser.Username + "'s project",
Replace name with `-` instead of 's

2023-09-13 07:19 UTC, SarthakJain26 commented on chaoscenter/authentication/api/handlers/rest/dex_auth_handler.go
> +					CreatedAt: time.Now().Unix(),
Please use UnixMilli instead of Unix in all the places

2023-09-13 09:53 UTC, SarthakJain26 approved these changes

2023-09-13 09:54 UTC, merged