Added some text occurrences in UI
litmuschaos/litmus pull request #4186
Opened 2023-09-22 18:11 UTC by nanu1605

Added some text occurrences in UI which are not added to `strings.en.yaml` for translation and replaced the occurrences with `getString(' ')` in `chaoscenter/web.` #4147

2023-09-22 18:13 UTC, nanu1605 commented
Hello @Saranya-jena, please take a look at the changes.

2023-09-25 16:38 UTC, namkyu1999 commented
Check DCO, please

2023-09-26 11:32 UTC, nanu1605 commented
@namkyu1999 Please take a look at this PR

2023-09-27 05:27 UTC, namkyu1999 requested changes
LGTM 🚀
I requested few changes
1. Can you resolve all the issues I mentioned?
2. Can you also make all these changes to `web/src/strings/types.ts`
3. After changes, Can you sort and check strings via `yarn strings:sort` and `yarn strings:check` ?

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/components/InputSlider/InputSlider.tsx
> +            data-testid={getString('rangesliderinput')}
```suggestion
            data-testid={getString('rangeSliderInput')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/strings/strings.en.yaml
> +rangesliderinput: rangeSliderInput
```suggestion
rangeSliderInput: rangeSliderInput
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddHubModalWizard/AddHubModalWizard.tsx
> +                    placeholder={getString('EnteryourPersonalAcessToken')}
```suggestion
                    placeholder={getString('enterYourPersonalAccessToken')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/strings/strings.en.yaml
> +EnteryourPersonalAcessToken: Enter your Personal Acess Token
```suggestion
enterYourPersonalAccessToken: Enter your Personal Access Token
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
> +                  placeholder={getString('criteriafordata')}
```suggestion
                  placeholder={getString('criteriaForData')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
> +                  placeholder={getString('criteriafordata')}
```suggestion
                  placeholder={getString('criteriaForData')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/strings/strings.en.yaml
> +criteriafordata: Criteria for data
```suggestion
criteriaForData: Criteria for data
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
> +              placeholder={getString('typeofdata')}
```suggestion
              placeholder={getString('typeOfData')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/strings/strings.en.yaml
> +typeofdata: Type of data
```suggestion
typeOfData: Type of data
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/strings/strings.en.yaml
>  udpatePassword: Update Password
```suggestion
updatePassword: Update Password
```

can you change it too with relevent files?

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
> +                placeholder={getString('criteriafordata')}
```suggestion
                placeholder={getString('criteriaForData')}
```

2023-09-27 05:27 UTC, namkyu1999 commented on chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
> +            placeholder={getString('criteriafordata')}
```suggestion
            placeholder={getString('criteriaForData')}
```

2023-09-27 08:05 UTC, nanu1605 commented
Will update the `web/src/strings/types.ts` ASAP

2023-09-28 19:50 UTC, nanu1605 commented
@namkyu1999 Should I go to folder `/chaoscenter/web` and run `yarn strings`?

2023-09-28 23:00 UTC, namkyu1999 commented
> @namkyu1999 To regenerate `type.ts` should I go to folder `/chaoscenter/web` and run `yarn strings`?

Hey @nanu1605 , go to the `/chaoscenter/web` and
`yarn strings:check` => check whether your strings are duplicated or not
`yarn strings:sort` => sort strings
`yarn build` => this is what you want

I recommend you doing all of them :)

2023-09-30 09:54 UTC, nanu1605 commented
@namkyu1999  Please take a look at this PR :)

2023-09-30 10:42 UTC, namkyu1999 approved these changes
LGTM 🚀🚀

2023-10-16 05:08 UTC, Saranya-jena approved these changes

2023-10-16 05:11 UTC, namkyu1999 approved these changes

2023-10-26 10:29 UTC, amityt approved these changes

2023-10-26 10:30 UTC, SahilKr24 approved these changes

2023-10-27 07:03 UTC, merged