feat: add tests cases for  chaoscenter web views
litmuschaos/litmus pull request #4248
Opened 2023-10-30 00:16 UTC by Freedisch

## Proposed changes

Added test cases for views in chaoscenter web 
- ErrorCheck.tsx
- ResestPassowrd.tsx
- Overview.tsx

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-10-30 03:01 UTC, Freedisch commented
![image](https://github.com/litmuschaos/litmus/assets/82499435/e71df9f0-a1bd-4b0c-9d38-80a4a446b8c6)

2023-10-31 07:18 UTC, S-ayanide requested changes

2023-10-31 07:18 UTC, S-ayanide commented on chaoscenter/web/src/views/ResetPassword/__tests__/ResetPassword.test.tsx
> +  });
Same review as before

2023-11-15 05:03 UTC, S-ayanide requested changes

2023-11-15 05:03 UTC, S-ayanide commented on chaoscenter/web/src/utils/testUtils.tsx
> +          <AppStoreContext.Provider
AppStoreContext Provider should be the top most in the order, here is the revised order for reference

```tsx
<AppStoreContext.Provider>
  <StringContext.Provider>
    <ReactQueryProvider>
       <ApolloProvider>
          <BrowserRouter />
       </ApolloProvider>
    </ReactQueryProvider>
  </StringContext.Provider>
</AppStoreContext.Provider>
```

2023-11-15 05:03 UTC, S-ayanide commented on chaoscenter/web/src/views/ResetPassword/__tests__/ResetPassword.test.tsx
> +/* eslint-disable @typescript-eslint/no-empty-function */
Please remove this eslint disable statement and fix any linting issues.

2023-11-15 05:10 UTC, hrishavjha approved these changes
Thanks for the change, apart from @S-ayanide 's comments rest looks good to me. Please address them🚀

2023-11-22 07:31 UTC, S-ayanide approved these changes
LGTM

2023-11-22 07:36 UTC, merged