Fix bug: Move the CUSTOM_TLS_CERT from subscriber config to subscribe…
litmuschaos/litmus pull request #4254
Opened 2023-11-02 10:52 UTC by RipulHandoo

…r secret

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
This PR solve's [this](https://github.com/litmuschaos/litmus/issues/3943).
It ```Move the CUSTOM_TLS_CERT from subscriber config to subscriber secret.```

2023-11-02 18:39 UTC, neelanjan00 approved these changes

2023-11-03 06:10 UTC, SarthakJain26 approved these changes

2023-11-06 05:18 UTC, Saranya-jena requested changes

2023-11-06 05:18 UTC, Saranya-jena commented on litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
> +  CUSTOM_TLS_CERT: "#{CUSTOM_TLS_CERT}"
You will need to make changes in Chaoscenter directory, litmus-portal directory will be deprecated soon

2023-11-06 05:58 UTC, closed without merging