chore: Added UI changes for enable and disable cron feature
litmuschaos/litmus pull request #4286
Opened 2023-11-08 12:19 UTC by amityt

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-11-10 06:25 UTC, Saranya-jena approved these changes

2023-11-10 07:13 UTC, arkajyotiMukherjee requested changes

2023-11-10 07:13 UTC, arkajyotiMukherjee commented on chaoscenter/web/src/controllers/ChaosStudioEdit/ChaosStudioEdit.tsx
> +          : (parsedManifest as CronWorkflow)?.spec?.suspend;
can we clean this up in a function with if statements instead of ternary

2023-11-10 07:13 UTC, arkajyotiMukherjee commented on chaoscenter/web/src/controllers/ExperimentRunDetails/ExperimentRunDetails.tsx
> +
isCronEnabled could be a func in of itself

2023-11-10 07:13 UTC, arkajyotiMukherjee commented on chaoscenter/web/src/controllers/ExperimentRunHistory/ExperimentRunHistory.tsx
> +
same

2023-11-12 20:59 UTC, namkyu1999 approved these changes

2023-11-15 03:59 UTC, arkajyotiMukherjee approved these changes

2023-11-15 05:26 UTC, S-ayanide approved these changes

2023-11-15 05:52 UTC, merged