refactor: Update subscriber to use Kubernetes patch for ConfigMaps an…
litmuschaos/litmus pull request #4287
Opened 2023-11-08 13:21 UTC by RipulHandoo

…d Secrets instead of get-update

## Proposed changes
In the ClusterRegister function within [operations.go](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go), I've replaced the 'update' method with 'kubernetes patch' for updating ConfigMaps and Secrets. This change involves using 'json.Marshal' to serialize the clusterData, which is then utilized in 'Patch' with 'MergePatchType' for both ConfigMap and Secret updates.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
This PR solve's this #3944

2023-12-01 08:50 UTC, Saranya-jena requested changes
Hey @RipulHandoo you would need to add the changes in `chaoscenter` directory since with the release of Litmus 3.0, litmus-portal dir has been deprecated.

2023-12-01 09:16 UTC, RipulHandoo commented
> Hey @RipulHandoo you would need to add the changes in `chaoscenter` directory since with the release of Litmus 3.0, litmus-portal dir has been deprecated.

Sure, I'll make the necessary changes in [this file](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/subscriber/pkg/k8s/operations.go#L158) shortly.

2023-12-01 14:05 UTC, RipulHandoo commented
> Hey @RipulHandoo you would need to add the changes in `chaoscenter` directory since with the release of Litmus 3.0, litmus-portal dir has been deprecated.

Hey @Saranya-jena, I have made necessary changes in the `chaoscenter` . Please review and let me know if everything is okay.

2024-01-05 06:19 UTC, Saranya-jena requested changes

2024-01-05 06:19 UTC, Saranya-jena commented on chaoscenter/subscriber/pkg/k8s/operations.go
> +			"IS_CLUSTER_CONFIRMED": true,
This should be `IS_INFRA_CONFIRMED`

2024-01-05 06:19 UTC, Saranya-jena commented on chaoscenter/subscriber/pkg/k8s/operations.go
> +	atype "subscriber/pkg/types"
please give it a meaningful name

2024-01-05 06:19 UTC, amityt approved these changes

2024-01-05 06:20 UTC, Jonsy13 commented on chaoscenter/subscriber/pkg/k8s/operations.go
> +	logrus.Info("%s has been updtaed", InfraConfigName)
```suggestion
	logrus.Info("%s has been updated", InfraConfigName)
```

2024-01-15 16:44 UTC, RipulHandoo commented on chaoscenter/subscriber/pkg/k8s/operations.go
> +			"IS_CLUSTER_CONFIRMED": true,
Corrected.

2024-02-12 06:39 UTC, Jonsy13 approved these changes

2024-02-12 06:39 UTC, Saranya-jena approved these changes

2024-02-12 06:44 UTC, SarthakJain26 approved these changes

2024-02-12 06:51 UTC, merged