chore: Refactored probe to make description optional, updated GetProbeYAML API, schema update for prom probe and bug fixes
litmuschaos/litmus pull request #4356
Opened 2023-12-21 03:57 UTC by S-ayanide

## Proposed changes

Refactored probe to make description optional, updated GetProbeYAML API, schema update for prom probe and bug fixes

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2023-12-26 11:54 UTC, namkyu1999 approved these changes

2024-01-02 08:44 UTC, Saranya-jena approved these changes

2024-01-02 09:08 UTC, Saranya-jena commented
@S-ayanide the backend checks are failing. Can you PTAL?

2024-01-02 09:25 UTC, SarthakJain26 requested changes

2024-01-02 09:25 UTC, SarthakJain26 commented on chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
>  	"encoding/json"
@S-ayanide please run go-fmt in this file

2024-01-02 09:25 UTC, SarthakJain26 commented on chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go
>  	"encoding/json"
@S-ayanide please run go-fmt in this file

2024-01-02 10:49 UTC, SarthakJain26 approved these changes

2024-01-02 11:55 UTC, merged