Implemented test case for JwtMiddleware #4418
litmuschaos/litmus pull request #4411
Opened 2024-01-25 12:22 UTC by nikzayn

## Proposed changes
- Expected to add the test cases for JWT Middleware 

## Types of changes
- Added the test cases for JWT Middleware

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)

## Dependency
- (#4410)

## Special notes for your reviewer:
- Retest the changes

2024-02-12 07:07 UTC, Saranya-jena commented
@nikzayn Can you please attach screenshots for the executed testcases and coverage?

2024-03-07 06:58 UTC, SarthakJain26 commented
@nikzayn please address the comments, so that we can merge this PR

2024-03-07 07:07 UTC, nikzayn commented
> @nikzayn Can you please attach screenshots for the executed testcases and coverage?

Sorry, for the delay. I was actually out of town. I came back yesterday. I will update you on the following soon..!

2024-03-07 07:07 UTC, nikzayn commented
> @nikzayn please address the comments, so that we can merge this PR

I will update for sure..!!

2024-03-08 08:00 UTC, nikzayn commented
Here are the screenshots of test execution and coverage output.

<img width="1185" alt="Screenshot 2024-03-08 at 1 11 49 PM" src="https://github.com/litmuschaos/litmus/assets/25152186/4a3ec332-f05c-403b-8e32-2eefb6a54f67">
![Screenshot 2024-03-08 at 1 27 35 PM](https://github.com/litmuschaos/litmus/assets/25152186/ecc33345-af01-461c-bc52-23041977c35e)

2024-03-08 12:00 UTC, SarthakJain26 requested changes

2024-03-08 12:00 UTC, SarthakJain26 commented on chaoscenter/authentication/api/middleware/jwt_middleware_test.go
> +func (m *MockApplicationService) AddMember(projectID string, member *entities.Member) error {
@nikzayn you can remove all these generated functions that are unimplemented.

2024-03-08 12:00 UTC, SarthakJain26 commented on chaoscenter/authentication/api/middleware/jwt_middleware_test.go
> +	t.Run("Missing Authorization Header", func(t *testing.T) {
I see there's 30% code coverage with this TC, please check if you can add more TCs for more code coverage

2024-03-08 12:00 UTC, SarthakJain26 commented on chaoscenter/authentication/api/middleware/coverage.html
> +
@nikzayn you can remove both the coverage files, you don't need to commit those generated files.

2024-04-09 08:29 UTC, Saranya-jena commented
@nikzayn are you still working on this PR?

2024-06-07 06:14 UTC, Saranya-jena commented
closing due to inactivity

2024-06-07 06:14 UTC, closed without merging