Adds docs for toleratios in source cmdProbe
litmuschaos/litmus pull request #4442
Opened 2024-02-15 13:30 UTC by Nageshbansal

## Proposed changes

Add docs for tolerations in source cmdProbe.
Fixes: [#482](https://github.com/litmuschaos/chaos-operator/issues/482)
Part of PR: [PR](https://github.com/litmuschaos/chaos-operator/pull/483)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2024-02-17 12:23 UTC, amityt requested changes
Requested a minor change, rest looks good!

2024-02-17 12:23 UTC, amityt commented on mkdocs/docs/experiments/concepts/chaos-resources/probes/cmdProbe.md
> +    <td>The <code>.tolerations</code> Flag to hold the Tolerations for the probe pod/td>
```suggestion
    <td>The <code>.tolerations</code> Flag to hold the Tolerations for the probe pod</td>
```

2024-02-21 07:29 UTC, amityt approved these changes

2024-02-23 06:52 UTC, Saranya-jena approved these changes

2024-03-01 08:52 UTC, ispeakc0de approved these changes

2024-03-01 09:50 UTC, namkyu1999 approved these changes

2024-03-01 10:36 UTC, merged