Added necessary rbacs for invite_users and get_project_members API
litmuschaos/litmus pull request #4697
Opened 2024-06-10 08:40 UTC by Saranya-jena

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2024-06-10 10:21 UTC, SarthakJain26 requested changes

2024-06-10 10:21 UTC, SarthakJain26 commented on chaoscenter/authentication/api/handlers/rest/project_handler.go
> +		err := validations.RbacValidator(c.MustGet("uid").(string), projectID,
Can you please add one more check here, if the user has admin role, then user can view the information.

2024-06-11 10:21 UTC, SarthakJain26 commented on chaoscenter/authentication/api/handlers/rest/project_handler.go
> +		if err != nil && entities.Role(userRole) != entities.RoleAdmin {
You can add the admin check before doing RbacValidator check. If role is admin, then you dont need teh RbacValidator

2024-06-19 08:42 UTC, Jonsy13 approved these changes

2024-06-21 05:38 UTC, SarthakJain26 approved these changes

2024-06-24 07:28 UTC, merged