Update README-ko.md file
litmuschaos/litmus pull request #4781
Opened 2024-07-21 06:21 UTC by suhyenim

## Proposed changes

Translate README.md file into Korean.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2024-07-23 07:11 UTC, namkyu1999 requested changes
Could you please check the reviews below? rest looks good to me :)

2024-07-23 08:27 UTC, suhyenim commented on translations/README-ko.md
> +- **ChaosResult**: A resource to hold the results of the experiment run. It provides details of the success of each validation constraint, the revert/rollback status of the fault as well as a verdict
Sure, I will check the reviews and commit the changes. Thank you :)

2024-07-23 08:46 UTC, namkyu1999 approved these changes
LGTM 🚀

2024-07-31 02:44 UTC, jongwooo reviewed
nit: It would be nice to have a Korean glossary. (e.g., [Kubernetes Korean glossary](https://kubernetes.io/ko/docs/contribute/localization_ko/#한글화-용어집-정보))

2024-08-08 14:18 UTC, neelanjan00 commented
@namkyu1999 are we good to merge this PR?

2024-08-08 14:24 UTC, namkyu1999 commented
> @namkyu1999 are we good to merge this PR?

Yes, looks good to me

2024-08-09 06:07 UTC, Saranya-jena approved these changes

2024-08-09 06:07 UTC, merged