Added the remoteHub field (for Git repository name) in the ChaosHub Frontend
litmuschaos/litmus pull request #4843
Opened 2024-08-22 10:31 UTC by JanhaviAlekar

## Proposed changes
![Screenshot from 2024-08-22 15-48-16](https://github.com/user-attachments/assets/fec9a1b8-6123-433e-8c23-4ceeb33b0efe)
![Screenshot from 2024-08-22 15-48-50](https://github.com/user-attachments/assets/a18b0926-f2bd-4136-8155-1aa510db0628)

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).
 #4842 
## Special notes for your reviewer:

2024-08-28 09:43 UTC, SahilKr24 requested changes

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/images/Bitbucket.svg
> +<svg width="800px" height="800px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill="none"><path fill="#2684FF" fill-rule="evenodd" d="M1.403 2.15A.43.43 0 011.73 2l12.54.002a.43.43 0 01.42
we can update height and width 32px for all svgs or just remove them if not required.

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/AddHubModalWizard/AddHubModalWizard.tsx
> +                    { label: 'Others', value: 'Others' }
strings

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/ChaosHubs/ChaosHubs.tsx
> +
instead of switching the `img` tag we can switch the `src` directly

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/ChaosHubs/ChaosHubs.tsx
> +
we can shift this to utils

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/AddHubModalWizard/AddHubModalWizard.tsx
> +                  label={<Text font={{ variation: FontVariation.FORM_LABEL }}>Remote Hub</Text>}
strings

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/ChaosHubs/ChaosHubs.tsx
> +import Bitbucket from '../../images/Bitbucket.svg';
import all from `@images`

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/ChaosHubs/ChaosHubs.tsx
> +                        <RemoteHubImage remoteHubName={chaosHub.remoteHub} />
we can pass `isDefault` too as a prop and get the correct icon

2024-08-28 09:43 UTC, SahilKr24 commented on chaoscenter/web/src/views/EditHubModalWizard/EditHubModalWizard.tsx
> +                  ]}
strings

2024-09-06 10:31 UTC, SahilKr24 approved these changes

2024-09-06 10:57 UTC, amityt approved these changes

2024-09-13 06:23 UTC, merged