[Feat] Add Helm Install Handler
litmuschaos/litmus pull request #4903
Opened 2024-09-24 02:04 UTC by dusdjhyeon

## Proposed changes

Create a chaos environment via helm agent even in an open source environment

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2024-10-05 07:20 UTC, namkyu1999 reviewed
Hi @dusdjhyeon , Could you let me know if you are planning to add frontend UI?

2024-10-05 12:19 UTC, dusdjhyeon commented
Hi, @namkyu1999 
I heard that someone else would be doing the front-end.ㅁ

2024-10-09 05:50 UTC, Jonsy13 commented
@andoriyaprashant Will be working on UI part of changes. We will take both PRs separately but merge on same day to avoid any breakages.

2025-09-16 10:02 UTC, SarthakJain26 approved these changes

2025-09-16 10:06 UTC, SarthakJain26 requested changes

2025-09-16 10:06 UTC, SarthakJain26 commented on chaoscenter/graphql/server/graph/model/models_gen.go
> +	InstallationType *string `json:"installationType,omitempty"`
There are changes in the models_gen.go, but no changes in the .graphqls file. How are these changes being generated?

2026-04-14 16:13 UTC, PriteshKiri commented
Hey @dusdjhyeon 

Are you still working on this issue?

2026-07-14 11:03 UTC, PriteshKiri commented
@dusdjhyeon, any updates?

2026-09-16 09:24 UTC, PriteshKiri commented
Closing due to inactivity

2026-09-16 09:24 UTC, closed without merging